# Generated by Django 4.2.4 on 2025-05-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
