# Generated by Django 4.2.4 on 2025-07-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='category.category'),
        ),
    ]
