# Generated by Django 4.2.4 on 2025-07-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
